name: CI

on:
  push: # on push commits at any branch
  pull_request: # on external PR
  workflow_dispatch: # on demand

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TRAVIS: 'true' # Skip tests requiring data
    strategy:
      matrix:
        python-version:
          - '3.11' # oldest supported Py3 (test use enterContext)
          - '3' # newest supported Py3
    name: Python ${{ matrix.python-version }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt update -qq

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -e .

      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            coveralls

      - name: Unit tests
        run: |
          pytest

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: python-${{ matrix.python-version }}

      - name: 📢 Notify status changes
        if: always()
        uses: vokimon/gha-notify-telegram@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
